config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new]
  resource :session, only: [:create, :new, :destroy]
  resources :subs
  resources :posts, except: :index do
    resources :comments, only: [:create, :new, :show]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author_id, :post_id, presence: true

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :post

  belongs_to :parent_comment,
    class_name: :Comment

  has_many :child_comments, dependent: :destroy,
    foreign_key: :parent_comment_id,
    class_name: :Comment
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true
  validate :url_in_right_format
  validate :post_sub_not_empty

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs
  has_many :comments, dependent: :destroy


  def url_in_right_format
    return if self.url.nil?
    unless self.url[0..6] == "http://"
      errors[:url] << "must start with http://"
    end
  end

  def post_sub_not_empty
    errors[:base] << "Post must belong to at least one sub" if self.subs == []
  end

  def master_comments
    self.comments.where("parent_comment_id IS NULL")
  end
end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :post, :sub, presence: true
  validates :post_id, uniqueness: {scope: :sub_id }

  belongs_to :post
  belongs_to :sub


end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :posts,
    through: :post_subs

  has_many :post_subs, dependent: :destroy, inverse_of: :sub
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  has_many :subs,
    foreign_key: :moderator_id

  has_many :comments,
    foreign_key: :author_id

  has_many :posts,
    foreign_key: :author_id

  attr_reader :password

  def self.find_by_credentials(username, pw)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(pw) ? user : nil
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    pwdigest = BCrypt::Password.new(self.password_digest)
    pwdigest.is_password?(pw)
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(32)
  end

  def ensure_session_token
    self.session_token ||= self.generate_session_token
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
    redirect_to subs_url
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
    redirect_to new_session_url
  end

  def logged_in?
    current_user ? true : false
  end

  def ensure_current_user
    redirect_to new_session_url unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find_by(id: params[:post_id])
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find_by(id: params[:post_id])
    @comment.author_id = current_user.id

    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find_by(id: params[:id])
    render :show
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_author, only: [:edit, :update, :destroy]
  before_action :ensure_current_user, only: [:new, :create]

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comments = @post.master_comments
    render :show
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @sub = @post.sub
    @post.destroy
    redirect_to sub_url(@sub)
  end

  def edit
    @post = Post.find_by(id: params[:id])
    render :edit
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def ensure_author
    @post = Post.find_by(id: params[:id])
    unless current_user.id == @post.author_id
      flash[:errors] = "BAD BAD!!!!"
      redirect_to sub_url(@post.sub)
    end
  end


end#class

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login_user!(@user)
    else
      flash.now[:errors] = ["Couldn't find user with those credentials"]
      render :new
    end
  end

  def destroy
    logout_user!
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_moderator, only: [:edit, :update, :destroy]
  before_action :ensure_current_user, only: [:new, :create]

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    @posts = @sub.posts
    render :show
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def ensure_moderator
    @sub = Sub.find_by(id: params[:id])
    unless current_user.id == @sub.moderator_id
      flash[:errors] = "BAD BAD!!!!"
      redirect_to subs_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\">".html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li>
  <%= link_to "#{comment.content}", post_comment_url(comment.post, comment) %>
</li>

<% unless comment.child_comments.empty? %>
  <% comments = comment.child_comments %>
  <ul>
    <%= render comments %>
  </ul>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<form action="<%=post_comments_url(@post)%>" method="post">
  <%= auth_token %>

  <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">

  <label>Body
    <textarea name="comment[content]" rows="8" cols="40"></textarea>
  </label>

  <input type="submit" name="Submit">
</form>

app/views/comments/show.html.erb
<h2>Reply:</h2>

<form action="<%=post_comments_url(@comment.post)%>" method="post">
  <%= auth_token %>

  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">

  <input type="hidden" name="comment[post_id]" value="<%= @comment.post.id %>">

  <label>Body
    <textarea name="comment[content]" rows="8" cols="40"></textarea>
  </label>

  <input type="submit" name="Submit">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <p>
    <% if flash[:errors] %>
      <ul>
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    <% end %>
  </p>

    <div><%=link_to "All Subs", subs_url%></div>
    <% if logged_in? %>
      <div>Logged in as: <%= current_user.username %></div>
      <div><%= link_to "Create a sub!", new_sub_url %></div>
      <div><%= button_to "Logout", session_url, method: :delete %></div>
    <% else %>
      <div><%= button_to "Sign in", new_session_url, method: :get %></div>
      <div><%= button_to "Register", new_user_url, method: :get %></div>
    <% end %>
</header>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% action = post.persisted? ? post_url(post) : posts_url %>
<% method = post.persisted? ? "patch" : "post" %>

<form action="<%=action%>" method="post">
  <input type="hidden" name="_method" value="<%=method%>">
  <%= auth_token %>

  <p>
    <label>Title:
      <input type="text" name="post[title]" value="<%= post.title %>">
    </label>
  </p>

  <p>
    <label>URL:
      <input type="text" name="post[url]" value="<%= post.url %>">
    </label>
  </p>

  <p>
    <label>Content:
      <textarea name="post[content]" rows="8" cols="40"><%= post.content %></textarea>
    </label>
  </p>

  <p>
    <label>Sub:
      <%Sub.all.each do |sub| %>
        <input type="checkbox" name="post[sub_ids][]" value="<%=sub.id%>" <%= post.subs.include?(sub) ? "checked" : "" %>> <%= sub.title %>
      <% end %>
    </label>
  </p>

  <input type="submit" name="submit">
</form>

app/views/posts/_post.html.erb
<li><%= link_to "#{post.title}", post_url(post) %></li>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>
<%= render "form", post: @post %>

app/views/posts/new.html.erb
<h1> New Post! </h1>
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<% if @post.url %>
  <h1><%= link_to "#{@post.title}", @post.url %></h1>
<% else %>
  <h1><%= @post.title %></h1>
<% end %>

<section>
  <b>Content:</b>
  <p>
    <%= @post.content %>
  </p>
</section>

<section>
  <b>Subs</b>
    <ul>
      <% @post.subs.each do |sub| %>
      <li><%= link_to "#{sub.title}", sub_url(sub) %></li>
      <% end %>
    </ul>
</section>

<h2>Comments</h2>
<%= link_to "Comment on this post!", new_post_comment_url(@post) %>

<ul>
  <%= render @comments %>
</ul>

<%= link_to "Edit Post", edit_post_url %>

app/views/subs/_form.html.erb
<% action = sub.persisted? ? sub_url(sub) : subs_url %>
<% method = sub.persisted? ? "patch" : "post" %>


<form action="<%=action%>" method="post">

  <input type="hidden" name="_method" value="<%=method%>">
  <%= auth_token %>
  <p>
    <label>Title:
      <input type="text" name="sub[title]" value="<%= sub.title %>">
    </label>
  </p>

  <p>
    <label>Description:
      <textarea name="sub[description]" rows="8" cols="40"><%= sub.description %></textarea>
    </label>
  </p>
  <input type="submit" name="submit">
</form>

app/views/subs/_sub.html.erb
<li>
  <%= link_to "#{sub.title}", sub_url(sub) %>
</li>

app/views/subs/edit.html.erb
<h1> Edit Sub </h1>
<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<h1>All the Subs!</h1>

<ul>
  <%= render @subs %>
</ul>

app/views/subs/new.html.erb
<h1> New Sub </h1>
<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<section>
  <b>Description</b>
  <p>
    <%= @sub.description %>
  </p>
</section>

<%= link_to "Make New Post!", new_post_url %>

<ul>
  <%= render @posts %>
</ul>

app/views/users/new.html.erb
<h1> Sign up! </h1>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  <p>
    <label>Username:
      <input type="text" name="user[username]" value="<%=@user.username%>">
    </label>
  </p>

  <p>
    <label>Password:
      <input type="password" name="user[password]">
    </label>
  </p>

  <input type="submit" name="Submit">
</form>